expressots/expressots

- .github/workflows/core-lib-ci-cd.yaml
> updated pipeline

- templates/non_opinionated/src/app.usecase.ts
- templates/opinionated/expressots.config.ts
- templates/opinionated/src/useCases/user/create/create-user.controller.ts
- templates/opinionated/src/useCases/user/findall/findall-user.usecase.ts
When creating a new project from the CLI, the downloaded templates include DTOs with incorrectly named imports.
The project has now been created correctly.
If this PR contains a breaking change, please describe the impact and migration path for existing …
> fix: template import errors from dtos

- .gitattributes
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Bugfix
warning message on git excluded gitattribute pattern …
> fix: remove exclude pattern

- packages/core/src/controller/base-controller.ts
- packages/core/src/error/error-handler-middleware.ts
- packages/core/src/error/report.ts
> fix: error handling

- .github/workflows/core-lib-ci-cd.yaml
- [x ] CI related changes
Try to auto publish npm package
Remove …
> fix: remove npm auto publish from ci

- packages/core/src/application/application.ts
- packages/core/src/controller/base-controller.ts
- packages/core/src/index.ts
- packages/core/src/render/handlebars.interface.ts
- packages/core/src/render/index.ts
- packages/core/src/render/render.type.ts
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
- [ x] Feature
Please describe the current behavior that you are modifying, or link to a …
> feat: add render engine mechanic and handlebars sup

- README.md
> Fix broken url on readme

- templates/opinionated/src/useCases/user/delete/user-delete.usecase.ts
- templates/opinionated/src/useCases/user/find/user-find.usecase.ts
- templates/opinionated/src/useCases/user/update/user-update.usecase.ts
- [x ] The commit message follows our guidelines:
- [x ] Other... Please describe:
Opinionated template user use …
> fix: add 404 on opinionated template user usecases

- packages/core/src/environment/env-validator.ts
- [x ] The commit message follows our guidelines:
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
- [ x] Refactoring (no functional changes, no api changes)
Please describe the current …
> Ets 272 remove from the env validator provider the check of all os env variables

- .github/ISSUE_TEMPLATE/community_ideas.yml
- [x ] The commit message follows our guidelines:
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
- [x ] CI related changes
Please describe the current behavior that you are modifying, or …
> feat: add community ideas form

- .github/workflows/community-idea.yml
- [ x] CI related changes
- [x ] No
If this PR contains a breaking …
> fix: add workflow for auto project and label

- .github/dependabot.yml
> feat: add dependabot for fetch new version of dependencies

- packages/core/src/application/application.ts
Graceful shutdown doesn't capture all events. 
Issue Number: #75 
We are able to …
> fix: increase the event range for graceful shutdown

- templates/opinionated/src/providers/db-in-memory/db-in-memory.provider.ts
- templates/opinionated/src/repositories/base-repository.ts
- templates/opinionated/src/repositories/user/user.repository.ts
InMemoryDB provider is hardcoded for User table and doesn't have the proper naming, it is described as UserDB rather than table.
Describe the new behavior or link to a …
> fix: add generic in memory db and virtual table analysis

- CHANGELOG.md
- package.json
- packages/core/src/application/application.ts
- packages/core/src/error/app-error.ts
- packages/core/src/error/error-handler-middleware.ts
- packages/core/src/error/index.ts
- packages/core/src/error/report.ts
> hotfix: middleware needs next parameter

- templates/opinionated/src/useCases/user/create/user-create.usecase.ts
- templates/opinionated/src/useCases/user/delete/user-delete.usecase.ts
- templates/opinionated/src/useCases/user/find/user-find.usecase.ts
- templates/opinionated/src/useCases/user/update/user-update.usecase.ts
> fix: use new report utility in usecases

- packages/core/src/console/console.ts
In `Console` class method currently has `messageServer` method. That method receive some params, one of those contains "port" param, but its type equals to `any`. This PR only changes type from `any` to `number`. Also we remove "no-explicit-any" eslint rule. …
> refactor: update type from any to number

- packages/core/src/provider/dto-validator/dto-validator.provider.ts
> fix: dto validator json structure per property

- packages/core/src/middleware/interfaces/cookie-parser.interface.ts
- packages/core/src/middleware/middleware-resolver.ts
- packages/core/src/middleware/middleware-service.ts
> Cookie Parser

- packages/core/src/middleware/index.ts
- packages/core/src/middleware/interfaces/serve-favicon.interface.ts
- packages/core/src/middleware/middleware-resolver.ts
- packages/core/src/middleware/middleware-service.ts
> Serve favicon

- CONTRIBUTING_HOWTO.md
> [doc fix]: Fixing typos

- packages/core/src/middleware/index.ts
- packages/core/src/middleware/interfaces/express-rate-limit.interface.ts
- packages/core/src/middleware/middleware-resolver.ts
- packages/core/src/middleware/middleware-service.ts
Currently there is no implementation for rate limit in codebase. 
Issue Number: #113
This PR adds functionality to use `express-rate-limit`
This PR is a draft …
> Feature: add rate limit middleware

- packages/core/src/middleware/middleware-service.ts
> fix conflict

- packages/core/src/middleware/index.ts
- packages/core/src/middleware/interfaces/helmet.interface.ts
- packages/core/src/middleware/middleware-resolver.ts
- packages/core/src/middleware/middleware-service.ts
Issue Number: #107
addHelmet() method added
If this PR contains a breaking change, please describe the impact and migration path for …
> Feat(core): add helmet middleware

- package.json
Currently manual setup of husky after code setup is necessary. This can be avoided though.
Issue Number: https://github.com/expressots/expressots/issues/121
Auto setup of the husky with installation and completion of `npm install` and hence removing overhead of setting up husky …
> fix: Auto setup husky with project setup and installation

- packages/core/src/middleware/index.ts
- packages/core/src/middleware/interfaces/express-session.interface.ts
- packages/core/src/middleware/middleware-resolver.ts
- packages/core/src/middleware/middleware-service.ts
Issue Number: https://github.com/expressots/expressots/issues/124
If this PR contains a breaking change, please describe the impact and …
> feat: Added express-session middleware for expressots

- packages/core/src/console/__tests__/console.spec.ts
- packages/core/src/provider/environment/__tests__/env-validator.spec.ts
- tsconfig.base.json
Issue Number: #128 
This pull request:
- Moves tests to `__tests__` folders closer to the tested features;
- Updates `exclude` in tsconfig;
- Fixes console test.
If this PR contains a …
> test: improve collocation and fix console tests

- .eslintrc.cjs
- packages/core/src/provider/db-in-memory/db-in-memory.provider.ts
- packages/core/src/provider/index.ts
R = N/A
R = Added DBInMemory as Provider
If this PR contains a breaking change, please describe the impact and …
> feat: add db in memory as provider

- templates/non_opinionated/package.json
- templates/opinionated/package.json
Updated reflect-metadata version
Updated reflect-metadata version
If this PR contains a breaking change, please …
> feat: update reflect metadata on templates

- templates/non_opinionated/.eslintrc.js
- templates/opinionated/.eslintrc.js
adding a new eslint rule to inferrable types
Currently the templates are complaining about type inference in classes …
> refactor: update eslint config inferrable types

- templates/non_opinionated/package.json
- templates/non_opinionated/tsconfig.build.json
- templates/non_opinionated/tsconfig.json
- templates/opinionated/package.json
- templates/opinionated/tsconfig.build.json
- templates/opinionated/tsconfig.json
Versions are set to update automatically
All libs versions are locked. User will have to manually change as desired …
> fix: lock versions, update to es2021

- package.json
N/A
Added prepublish script in `package.json`
If this PR contains a breaking change, please describe the impact and …
> ci: add prepublish script

- templates/non_opinionated/package.json
- templates/opinionated/package.json
Currently the commands are exposed directly to user
```
"prebuild": "rm -rf ./dist",
"build": "tsc -p tsconfig.build.json && cp -R ./register-path.js tsconfig.build.json package.json …
```
> refactor: add expressots project commands

- templates/non_opinionated/package.json
- vitest.config.ts
> refactor: separate template tests from core

- templates/non_opinionated/package.json
- templates/opinionated/package.json
> refactor: update express types

- package.json
- packages/core/src/application/__tests__/application-container.spec.ts
- packages/core/src/application/__tests__/application-factory.spec.ts
- packages/core/src/common/__tests__/package-resolver.spec.ts
- packages/core/src/common/__tests__/project-config.spec.ts
- packages/core/src/console/__tests__/console.spec.ts
- packages/core/src/container-module/__tests__/container-module.spec.ts
- packages/core/src/container-module/container-module.ts
- packages/core/src/controller/__tests__/base-controller.spec.ts
- packages/core/src/decorator/__tests__/scope-binding.spec.ts
- packages/core/src/error/__tests__/app-error.spec.ts
- packages/core/src/error/__tests__/error-handler-middleware.spec.ts
- packages/core/src/error/__tests__/report.spec.ts
- packages/core/src/error/__tests__/status-code.spec.ts
- packages/core/src/middleware/__tests__/middleware-resolver.spec.ts
- packages/core/src/middleware/__tests__/middleware-service.spec.ts
- packages/core/src/provider/__tests__/provider-manager.spec.ts
- packages/core/src/provider/db-in-memory/__tests__/db-in-memory.spec.ts
- packages/core/src/provider/dto-validator/__tests__/dto-validator.spec.ts
- packages/core/src/provider/environment/__tests__/env-validator.spec.ts
- tsconfig.base.json
- vitest.config.ts
Code coverage below 10%
Code coverage above 80%
If this PR contains a breaking change, please describe the impact and …
> 128 implement unit test for core

- .github/workflows/build.yml
- package.json
- vitest.config.ts
No CI action for code coverage
codecov action coverage
If this PR contains a breaking change, please describe the …
> feat: add code coverage report

- templates/non_opinionated/jest.config.ts
- templates/non_opinionated/package.json
- templates/opinionated/jest.config.ts
- templates/opinionated/package.json
- templates/opinionated/tsconfig.json
N/A
Updated project dependencies as well as jest configuration to include `rootDir` path as root `./`
If this PR …
> refactor: update dependencies and jest config

- .eslintrc.cjs
- .github/PULL_REQUEST_TEMPLATE.md
Conflict between vitest and eslint and PR github template not streamlined process
- Removed conflict between vitest …
> refactor: remove vitest/eslint conflict, review pr template

- package.json
- packages/core/src/application/application-factory.ts
> feat: update adapter express ver

- package.json
>
Update adapter-express version to 1.4. This version includes few performance improvements and the …
> refactor: update adapter version to 1.4

- package.json
>
Changed the node engine version to 18.18 and removed the "install" from "husky install" command as …
> fix: engine bump & husky init script

- packages/core/src/application/__tests__/application-container.spec.ts
- packages/core/src/application/__tests__/application-factory.spec.ts
- packages/core/src/container-module/__tests__/container-module-scope.spec.ts
- packages/core/src/controller/__tests__/base-controller.spec.ts
>
Increased code coverage for:
- application container
- application factory
- base controller
- …
> test: increase code coverage

- packages/core/src/provider/db-in-memory/__tests__/base-repo.spec.ts
- packages/core/src/provider/db-in-memory/base-repo.repository.ts
- packages/core/src/provider/index.ts
>
Polished the InMemory DB Provider to be used in the new plugin system. Now users can register the …
> 256 reimplement db in memory provider

- packages/core/src/application/application-factory.ts
- vitest.config.ts
> test: ignore spec on coverage & better comments in app-factory

- packages/core/src/middleware/index.ts
- packages/core/src/middleware/interfaces/url-encoded.interface.ts
- packages/core/src/middleware/middleware-resolver.ts
- packages/core/src/middleware/middleware-service.ts
> feat: add urlEncodedParser default middleware

- package.json
- packages/core/src/middleware/__tests__/middlewares.spec.ts
- vitest.config.ts
> test: ignore middleware service, utils

- packages/core/src/application/application-container.ts
- packages/core/src/common/__tests__/server-env.spec.ts
- packages/core/src/common/index.ts
- packages/core/src/common/server-env.types.ts
>
- Remove `reflect-metadata` from `main.ts`
- Added ServerEnvironment in Core
Any other information …
> fix: remove reflect-metadata from main, add server env types

- templates/non_opinionated/.gitignore
- templates/non_opinionated/src/main.ts
- templates/opinionated/.gitignore
- templates/opinionated/src/main.ts
> refactor: update templates main.ts removing reflect and serverenv type
